name: image_registration_legacy
channels:
  - simpleitk
  - anaconda
  - defaults
dependencies:
  - simpleitk=1.2.4

  # - blas=1.0=mkl
  # - ca-certificates=2022.4.26
  # - certifi=2021.5.30
  # - cycler=0.11.0
  # - et_xmlfile=1.1.0
  # - freetype=2.10.4
  # - glob2=0.7
  # - hdf5=1.8.20
  # - icc_rt=2019.0.0
  # - icu=58.2
  # - intel-openmp=2022.0.0
  # - jpeg=9b
  # - kiwisolver=1.3.1
  # - libopencv=3.4.2
  # - libpng=1.6.37
  # - libtiff=4.1.0
  # - lz4-c=1.9.3
  # - matplotlib=3.3.4
  # - matplotlib-base=3.3.4
  # - mkl=2019.4=245
  # - mkl-service=2.3.0
  # - mkl_fft=1.3.0
  # - mkl_random=1.1.0
  # - numpy=1.19.2
  # - numpy-base=1.19.2
  # - olefile=0.46=py36_0
  # - opencv=3.4.2
  # - openpyxl=3.0.9
  # - openssl=1.0.2u
  # - pandas=1.1.5
  # - pillow=8.3.1
  # - pip=21.2.2
  # - py-opencv=3.4.2
  # - pyparsing=3.0.4
  # #- pyqt=5.9.2
  # - python=3.6.13
  # - python-dateutil=2.8.2
  # - pytz=2021.3
  # #- qt=5.9.6
  # - scipy=1.5.2
  # - setuptools=58.0.4
  # - sip=4.19.25
  # - six=1.16.0
  # #- sqlite=3.38.5
  # #- tk
  # #- tornado=6.1
  # #- vc=14.2
  # #- vs2015_runtime=14.27.29016
  # - wheel=0.37.1
  # #- wincertstore=0.2
  # - xz=5.2.5
  # - zlib=1.2.11
  # - zstd=1.4.4
  - pip:
      - cached-property==1.5.2
      - h5py==3.1.0
      - mat73==0.59
